- name: load greeting.yml for Raju
  ansible.builtin.import_tasks: greeting.yml
  vars:
    sname: Raju

- name: load greeting.yml for Rahul
  ansible.builtin.import_tasks: greeting.yml
  vars:
    sname: Rahul


