- name: load greeting.yml for Raju
  ansible.builtin.import_tasks: greeting.yml
  vars:
    sname: Raju

- name: load greeting.yml for Rahul
  ansible.builtin.import_tasks: greeting.yml
  vars:
    sname: Rahul


- name: Load a tasks file dynamically
  ansible.builtin.include_tasks: "{{ filename }}.yml"
  vars:
    filename: greeting

- name: Import a role statically
  ansible.builtin.import_role:
    name: demo

- name: Import a role statically but another task file
  ansible.builtin.import_role:
    name: demo
    tasks_from: hello


